### ISSUE TITLE
"Validation" von Field und Plot - Anzeige für Benutzer, ob GS-Berechnung überhaupt möglich ist

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#105]
also z.B.: kein Bodenprofil, keine Wetterstation, Startdaten (mindestens eins davon), Pflanze, ..?

**UPDATE**
aus #88 rausgenommen:
"Speichern" geht nur, wenn
 .. Wetterdatenstation
 .. Bodenprofil
 .. Pflanze
 .. Bodenstartdatum oder Pflanzenstartdatum
vorhanden sind!

BodenstartWERT ist optional ( = default 100% )

**Comment by de-cgs-online-cwitzke** [comment]
Teil 1, bei der Eingabe von Werten abfangen, dass alles nötige gesetzt ist, ist erledigt.
Teil 2: Beim Versuch eine Empfehlung zu bekommen checken, ob alles nötige vorhanden ist (ohne Plot, keine Bewässerung), folgt!
