### ISSUE TITLE
Nach dem Speichern und einem anschließenden Neustart, sind Farm, Feld und Plot doppelt vorhanden

### ISSUE THREAD

**Issue by Gemuesebau** [Gemuesebau/GSEHEN#121]

**Comment by de-cgs-online-cwitzke** [comment]
Der Bug scheint zwischenzeitlich "nebenbei" behoben worden zu sein.
Eine Reproduktion war mir nicht mehr möglich.
Issue wird vorerst in "Wait" verschoben und in 7 Tagen geschlossen, sollte der Bug nicht wieder aufgetreten sein.
