### ISSUE TITLE
Rendering von Message(Format)s: Interpretieren von Objects als char verhindern

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#124]
Die merkwürdigen "kryptischen" Zeichen an Platzhalterstellen in RecommendedAction-Meldungen lassen vermuten, dass u.U. eine Interpretation als `char` erfolgt, welche auf jeden Fall verhindert werden muss.

Bei Zahlen (`instanceof Number`??) gilt für uns:
`.doubleValue()`, wenn Zahl ein Double ist
 SONST
`.integerValue()`
(`float` sollten wir nirgendwo haben)

**Comment by de-cgs-online-cwitzke** [comment]
Möglicherweise wurde dieser Bug beim Erstellen des Plugins automatisch behoben.

**Comment by de-cgs-online-atappe** [comment]
Kann aktuell nicht nachvollzogen werden.
