### ISSUE TITLE
Grafische Darstellung von Regen, Bewässerung, Defizit, Datum der Bewässerungsempfehlung (Add-On/Teil von Use Case 6)

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#143]
@Gemuesebau bitte Minimalanforderungen für die Grafik sowie Art und Weise des Aufrufs und Ort der Darstellung (Tab?) beschreiben.

![Visualisierungsbeispiel](https://user-images.githubusercontent.com/35488642/48341153-a2fac500-e66c-11e8-9e93-cd6db7cf679f.png)
als Beispiel und Diskussionsbasis

**Gemuesebau commented on 15 Aug** (2019)
_Die Grafik wird nicht aktualisiert... und sieht nicht so aus wie besprochen_

https://jira.cgs-online.de/browse/GSEH-29

@Gemuesebau bitte die Skizze, wie es aussehen sollte, anfügen

**Comment by Gemuesebau** [comment]
Die Grafik wird nicht aktualisiert... und sieht nicht so aus wie besprochen

**Comment by de-cgs-online-atappe** [comment]
**Gemuesebau commented on 15 Aug** (2019)
_Die Grafik wird nicht aktualisiert... und sieht nicht so aus wie besprochen_

https://jira.cgs-online.de/browse/GSEH-29
