### ISSUE TITLE
Menü-Führung verhält sich nicht wie erwartet

### ISSUE THREAD

**Issue by Gemuesebau** [Gemuesebau/GSEHEN#155]
Die Menüfuhrung ist noch etwas hakelig - wir sollten dort nocheinmal überprüfen was bei Klicks und Doppelklicks auf die DropDown Liste passiert und was angezeigt wird auf den Reitern Fieldview und Plotview wenn kein Feld oder Plot ausgewählt wurde aber auf die Reiter geklickt wurde.

https://jira.cgs-online.de/browse/GSEH-32

**Comment by de-cgs-online-atappe** [comment]
Wenn die MapView aktiv ist, bewirken Single-Clicks im Tree, dass das jeweilige Element ins Zentrum der Anzeige bewegt und etwas herangezoomt wird.
Wenn eine andere View aktiv, und im Fall von Field* und Plot* nicht leer, ist, bewirken Single-Clicks im Tree, dass das jeweils angeclickte Element in der dazu passenden View angezeigt wird.
Ein Double-Click macht das Gleiche, nur wird zusätzlich das angeclickt Tree-Element ein- oder ausgeklappt, je nach dessen aktuellem Zustand.
