### ISSUE TITLE
Plot View: Tabelle der Kulturparameter: Durchwurzelbare Zone wird falsch dargestellt

### ISSUE THREAD

**Issue by Gemuesebau** [Gemuesebau/GSEHEN#156]
**Gemuesebau commented on 15 Aug** (2019)
_Die Durchwurzelbare Zone wird als Double in der Tabelle angeziegt erlaubt aber nue eine Integer zuweisung_

https://jira.cgs-online.de/browse/GSEH-33

**Comment by Gemuesebau** [comment]
Die Durchwurzelbare Zone wird als Double in der Tabelle angeziegt erlaubt aber nue eine Integer zuweisung

**Comment by de-cgs-online-atappe** [comment]
Formatierung für `rootingZone` bei der Population der View-Bean von
dezimal auf int geändert ( = einfach `String.valueOf(...)` )
