### ISSUE TITLE
Plot View: Änderungen der editierbaren Felder wird nicht gespeichert

### ISSUE THREAD

**Issue by Gemuesebau** [Gemuesebau/GSEHEN#157]
**Gemuesebau commented on 17 Sep** (2019)
_Jegliche Änderungen im Plotview von Dauer in Tagen (Umstelltermin), Durchwurzelbare Zone werden nicht gespeichert._

https://jira.cgs-online.de/browse/GSEH-34

**Comment by Gemuesebau** [comment]
Jegliche Änderungen im Plotview von Dauer in Tagen (Umstelltermin), Durchwurzelbare Zone werden nicht gespeichert.

**Comment by de-cgs-online-atappe** [comment]
Das kann nicht nachvollzogen werden. Bitte Breakpoint in der savePlot setzen und Fehler reproduzieren. Bei uns läuft es durch, aber vllt. gibt es spezielle Situationen, in denen Information aus einem Debugging dann hilfreich wären.
