### ISSUE TITLE
Anzeige Wetterdaten: Stand, letzte Aktualisierung

### ISSUE THREAD

**Issue by Gemuesebau** [Gemuesebau/GSEHEN#160]
Es ist dem Anwender nicht ersichtilch auf welchem Wetterdatenstand die Anwendung die Berechungen vornimmt. Dies sollte angezeigt werden: Vorschlag als Fenstertext in der unteren rechten Ecke,

https://jira.cgs-online.de/browse/GSEH-35

**Comment by de-cgs-online-atappe** [comment]
Die Anwendung hat keine Statuszeile. Allein für diese Information eine einzuführen, erscheint zu aufwändig und verschwendet ggf. auch Platz. Es gibt bestimmt einen besseren Ort, an dem dann lediglich eine Zeile zu bestehendem Text hinzugefügt werden muss?

![grafik](https://user-images.githubusercontent.com/35488642/67750033-ab3f4200-fa2e-11e9-8c54-a3169ccc8b2e.png)
