### ISSUE TITLE
Datenbankverbindung/(Test-)Daten erstellen

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#17]
_"Datenbank Einträge hinzufügen, komplettieren, Beispiel-/Testdaten erstellen"_
s.a. #12 insofern, als auf dem Weg evtl. Daten(datei)manipulation möglich sein könnte.

im Falle JSON vllt. doch per Lib? https://www.journaldev.com/2324/jackson-json-java-parser-api-example-tutorial

**Comment by de-cgs-online-atappe** [comment]
- Wetterdaten
- kc-Werte
- Felder
(s.a. Ausschreibung!)

**Comment by de-cgs-online-cwitzke** [comment]
Die Datenbankverbindung MUSS nun hergestellt und implementiert werden.
