### ISSUE TITLE
TreeView: Logische Ansicht der Domänenobjekte (Auswahl von Farm / Feld / Plot)

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#22]
Benutzer können (und müssen) neue Felder und Plots erst im Objektbaum (TreeView) geeignet zuordnen/verschieben.

Ausblick: FarmView führt Zoom & Pan zu dem/den markierten Objekt(en) aus. --> #40

**Comment by de-cgs-online-atappe** [comment]
aus #25 "Logische Objektstruktur als Baumansicht" übernommen:

Gemeint ist, dass eine Baumansicht ausgehend von Farmen alle benötigten (d.h. in Java: annotierten?!) Unterobjekte (Collections) und Eigenschaften anzeigt bzw. editierbar macht.
Aktionen auf Knoten des Baums könnten evtl. in der Admin-Konsole #12 "on-the-fly" hinterlegt werden ..?

**Comment by de-cgs-online-cwitzke** [comment]
Prinzipiell "fertig".
Genauer Reiter im Accordion, sowie ContextMenu/allgemeine Aktionen darin sind noch offen, daher noch kein Close.

**Comment by de-cgs-online-cwitzke** [comment]
TTV reparieren. Löschen funktioniert nicht mehr; Mehrfachauswahl ist komplett buggy… → GsehenTreeTable.java, Zeile 138: skipClass nutzen!?
