### ISSUE TITLE
FarmView: Polygone, Farben, evtl. Tooltip, Zoom&Pan, evtl. Kontextmenü

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#23]
Bezug zu #1

**Comment by de-cgs-online-atappe** [comment]
Die (Eck-)Punkte der Polygone haben folgende Koordinaten(typen):
```java
double lat;  // z.B. 52.2678302894808
double lng;  // z.B. 10.51279688354498
```

d.h. Koordinaten im WGS84 Double-Format - nördliche Breite, östliche Länge
(südliche Breite hätte dann ein negatives Vorzeichen bei gleichem Betrag; sinngemäß für die Länge)

**Comment by de-cgs-online-cwitzke** [comment]
Statt Ampel (bei Plots): Blau (Bewässert, also alles tutti.) → Lila (In den kommenden 1-3 Tagen muss bewässert werden.) → Rot (Heute bewässern!)
