### ISSUE TITLE
Menüpunkt "Beenden", sowie das Schließen des Fensters, führen zu identischem Verhalten

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#29]
D.h., in der Anwendung auf das Beenden lauschen.
Sauberes "Herunterfahren"; also z.B. Speichern der Daten (ggf. nach Rückfrage).

https://jira.cgs-online.de/browse/GSEH-24

**Comment by de-cgs-online-cwitzke** [comment]
Läuft bislang.
TODO: Via GsehenFileChooser.java eine .js im Stil der vorhandenen erstellen.

**Comment by de-cgs-online-cwitzke** [comment]
#47 als Spezialisierung
