### ISSUE TITLE
JUnit Testklasse für den Haupt-Methodenaufruf, der (in R) [FAO56] FAO.ref implementiert

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#5]
```java
// Aufruf ungefähr so, Assert fehlt noch, und die Testmethode muss vermutlich mit @Test annotiert werden. Inhalt:
FAO56Calculator.calcRef(1.5, 54.3, 21.3, 123.4, new Date(), 18.7, 75.4, 25.2, 20.4, null, null);
```

**Comment by Gemuesebau** [comment]
Habe die benötigten jars in den lib ordner kopiert - leider funktioniert das mit eclipse nicht so einfach - standardmäßig sind die automtisch erstellten Test-Klassen und -Methoden private und lassen sich nur evaluieren wenn man die JUnit 5 library über das Kontextmenü hinzufügt. Für die Evaluierung mit manuell hinzugefügtem JUnit 5 muss man diese als public deklarieren - warum auch immer ...

**Comment by Gemuesebau** [comment]
Habe die benötigten jars in den lib ordner kopiert - leider funktioniert das mit eclipse nicht so einfach - standardmäßig sind die automtisch erstellten Test-Klassen und -Methoden private und lassen sich nur evaluieren wenn man die JUnit 5 library über das Kontextmenü hinzufügt. Für die Evaluierung mit manuell hinzugefügtem JUnit 5 muss man diese als public deklarieren - warum auch immer ...
