### ISSUE TITLE
Wetterdaten als CSV: im Hintergrund laufender automatisch angestoßener Import

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#51]
allgemeineres Issue: #15
Konfiguration(sdialog): #52
Anzeige Datenstand / letzter Berechnungslauf: #160

**Gemuesebau commented on 24 Oct** (2019)
_Der automatische import scheint nicht zu laufen.  - Gibt es die Mölichkeit eine Hinweis zu ziegen wenn der import erfolgt ist?_

https://jira.cgs-online.de/browse/GSEH-21

**Comment by Gemuesebau** [comment]
Der automatische import scheint nicht zu laufen.
