### ISSUE TITLE
Logger events für alle möglichen Events in Daily und Total balance einfügen

### ISSUE THREAD

**Issue by Gemuesebau** [Gemuesebau/GSEHEN#86]

**Comment by Gemuesebau** [comment]
Das logging hatte die Anwedung verlangsamt. Ist es hier noch notwendig weitere Logs zu schreiben und wenn Ja wie verhindert man eine derarte Verlangsamung der APP?

**Comment by de-cgs-online-atappe** [comment]
Die angepasste Logging-Konfiguration bewirkt, dass in der Logdatei nur Logs ab "INFO" gespeichert werden, und in der Konsole auch noch "CONFIG" angezeigt wird. "FINE" erscheint damit aktuell nirgendwo mehr. Z.B. werden Details zu einem evtl. PostgreSQL-Verbindungsfehler nur noch als "FINE" geloggt und stören dann die Ausgabe beim Anwendungsstart nicht mehr. _Für Debug-Logging_ kann damit "FINE" benutzt werden (muss dann aber temporär auch in der logging.properties für den ConsoleHandler ebenfalls auf "FINE" gestellt werden), oder "CONFIG", wenn die Menge überschaubar ist.
