### ISSUE TITLE
Buttons, die "lediglich" ein Objekt übernehmen, aber nicht (DB-mäßig) persistieren, sollten mit "Übernehmen und Schließen" ("Apply and Close") beschriftet werden

### ISSUE THREAD

**Issue by de-cgs-online-atappe** [Gemuesebau/GSEHEN#96]
Ein echtes "Speichern" (im Sinne der Persistenz) findet nur über Menü (oder beim Schließen der Anwendung) statt.

**Comment by de-cgs-online-cwitzke** [comment]
Buttons wurden mit "Übernehmen" beschriftet.
"Übernehmen und Schließen" könnte zum Irrglauben führen, die Anwendung damit zu schließen.
